### ISSUE TITLE
Feature: Implement Thread view

### ISSUE THREAD

**Issue by Giszmo** [Giszmo/nostroid#12]
When selecting an event, show the full context:

* The 5 Notes this was a reply to
* Indicator if the first Note was not the start of the thread
* Way to load more
* Show the selected Note with slightly larger font
* Show 10 replies, each displayed like beginning of a thread or in other words, not connected with lines or anything.
* Show "load more ..." where the 11th would be
* Each reply that itself has replies should indicate the number of replies
* Show the most relevant first reply, connected with a line

**Comment by louishuddleston** [comment]
@Giszmo is this complete for MVP?

**Comment by Giszmo** [comment]
There are other issues like #63 that need to get fixed for MVP. This here can be closed.
