### ISSUE TITLE
Feature: New Text Note

### ISSUE THREAD

**Issue by Giszmo** [Giszmo/nostroid#15]
Let the user create a new thread / Text Note. This probably comes before #10

**Comment by louishuddleston** [comment]
@Giszmo How do you want to handle tagging other users in notes?

**Comment by Giszmo** [comment]
@louishuddleston like Astral does it: Provide a list of all known profiles filtered by the user input after the `@`. The filter should consider nip05 and name (and later also nostr's "pet names" but that's MVP+2).

Users only need to be able to mention known profiles. As the app explores the follows graph to at least 10k users and also retains profiles outside the follows graph, the occasional mention of `@scammerXY` may turn out more difficult. Here, `@<pubkey>` should work for all mentions.

Nostr allows tagging without mentioning. This could be accomplished by providing a secondary text input that allows the user to enter space separated mentions. This input should only open when pressing the "tag" button and the list should not show the mentions or show them without a way to delete them.

I'm undecided whether the user should get to edit the "default" tags. For MVP I would say "no". Nostr clients currently add all p-tags and the author of the event being replied to to the new event. So a reply to a conversation between Alice, Bob and Carol would by default contain tags for these three already.

If it's easier, the tagging can also be a list view, showing color-coded the default tags first, the mentions second, both without a way to delete them and the additional tags afterwards.

**Comment by louishuddleston** [comment]
@Giszmo what does this require for MVP?

**Comment by Giszmo** [comment]
This is good enough for MVP. We'll make it smoother later.
