### ISSUE TITLE
Feature: Mobile Friendly Layout

### ISSUE THREAD

**Issue by Giszmo** [Giszmo/nostroid#22]
The current layout is the SvelteKit "Hello World" app. This needs to be turned into a mobile friendly layout, so that on small screens elements get arranged differently than on the big screen.

Astral does a good enough job here. As always, Twitter would be the primary reference.

**Comment by ralyodio** [comment]
Please assign to me. I'll work on it this weekend.

**Comment by ralyodio** [comment]
@Giszmo can we close this? Or is there more work to do?

**Comment by Giszmo** [comment]
Most things are good enough for MVP. The only annoying part is that the profiles page is not scrollable. At least not easily. Please add some "drag handle" to the profiles such that d&d only happens on them and scroll otherwise.
