### ISSUE TITLE
sqlite via wasm worker

### ISSUE THREAD

**Issue by userquin** [Giszmo/nostroid#50]
@Giszmo just a reminder if you want to give it a try: https://sqlite.org/wasm/doc/tip/about.md

**Comment by Giszmo** [comment]
Sounds like work in progress and limited to very few browsers - only chromium. Thanks for headsup anyway.

**Comment by userquin** [comment]
> Sounds like work in progress and limited to very few browsers - only chromium. Thanks for headsup anyway.

your favorite browser ;)

**Comment by Giszmo** [comment]
My daily driver is firefox but for nostroid chrome will be highly relevant due to PWA but I think it's not ok to break compatibility with Firefox, so for now I would close this issue.
