### ISSUE TITLE
production build is broken

### ISSUE THREAD

**Issue by Giszmo** [Giszmo/nostroid#7]
Running `pnpm run dev` much more works than running `pnpm run build && pnpm run preview`. @vishalxl is working on this with partial success so far in his master branch.

**Comment by vishalxl** [comment]
<img width="1280" alt="2022-09-26 (1)" src="https://user-images.githubusercontent.com/64505169/192205539-ea49587f-fd8c-4351-815e-ec3db3f9fb14.png">

The original error: 'global.process' is found to be undefined.

**Comment by vishalxl** [comment]
Adding 
```
	define: { 
		'global.process':  JSON.stringify('window.process')
	}
```
To vite.config.ts seems to work. Testing it right now. 

This line replaces the use of `global.process` everywhere with `window.process`.

**Comment by vishalxl** [comment]
On windows, I've tested with all three browsers chrome, edge and firefox, that the JSON.stringify line fixes the npm build issue.

**Comment by Giszmo** [comment]
This issue was fixed.
